name=IoTeye
version=3.0.0
author=Bogdan Shults (aka K1joL)
liense=MIT
maintainer=Bogdan Shults (aka K1joL) <k1jol@mail.ru>
sentence=A library for interacting with the IoTeye server.
paragraph=This library allows you to easily manage virtual pins and communicate with the IoTeye server.
category=Communication
url=https://github.com/K1joL/IoTEYE_API
architectures=esp8266